//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLibrary.Helpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library
    {
        public int ID_card { get; set; }
        public Nullable<int> ID_readers { get; set; }
        public string Book_title { get; set; }
        public Nullable<System.DateTime> Data_issue { get; set; }
        public System.DateTime Data_return { get; set; }
    
        public virtual Reader Reader { get; set; }
    }
}
