//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLibrary.Helpers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EducationalEntities : DbContext
    {
        public EducationalEntities()
            : base("name=EducationalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Library> Library { get; set; }
        public virtual DbSet<Reader> Reader { get; set; }

        private static EducationalEntities _context;
        public static EducationalEntities GetContext()
        {
            if (_context == null)
                _context = new EducationalEntities();
            return _context;
        }

    }
}
