//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp.Helpers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EducationalEntities : DbContext
    {
        public EducationalEntities()
            : base("name=EducationalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        internal static EducationalEntities GetContext()
        {
            throw new NotImplementedException();
        }

        public virtual DbSet<Library> Library { get; set; }
        public virtual DbSet<Reader> Reader { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
